receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

  debug: # Substituindo logging por debug
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]  # Substituindo logging por debug
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
