{
 "title": "Conversão e Performance - eShop",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Taxa de Conversão (Views → Add to Cart)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(basket_add_to_cart_count_total) / sum(catalog_product_view_count_total)) * 100\r\n",
     "legendFormat": "Conversion Rate (%)"
    }
   ]
  },
  {
   "title": "Taxa de Remoção do Carrinho",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(basket_remove_from_cart_count_total / basket_add_to_cart_count_total) * 100",
     "legendFormat": "Remove Rate (%)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "basket_add_to_cart_count_total", "legendFormat": "Add To Cart" },
    {
     "expr": "(sum(basket_add_to_cart_count_total) / sum(catalog_product_view_count_total)) * 100",
     "legendFormat": "View -> Add"
    },
    {
     "expr": "catalog_product_view_count_total",
     "legendFormat": "Catalog Views"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basket_remove_from_cart_count_total ",
     "legendFormat": "Remove From Cart"
    },
    {
     "expr": "(basket_remove_from_cart_count_total / basket_add_to_cart_count_total) * 100",
     "legendFormat": "Cart -> Bin"
    },
    { "expr": "basket_add_to_cart_count_total", "legendFormat": "Add To Cart" }
   ]
  },
  {
   "title": "Tempo Médio de Resposta do Add to Cart",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(add_to_cart_response_time_milliseconds_sum[5m])) / sum(rate(add_to_cart_response_time_milliseconds_count[5m])))",
     "legendFormat": "Latência média de requisições de Add to Cart (ms)"
    }
   ]
  },
  {
   "title": "Distribuição dos Tempos de Resposta do Add to Cart",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(add_to_cart_response_time_milliseconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}