{
 "title": "Métricas Gerais - eShop",
 "panels": [
  {
   "title": "Total de Requisições à API do Catálogo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "catalog_requests_total",
     "legendFormat": "Número total de requisições ao Catalog.API"
    }
   ]
  },
  {
   "title": "Total de Detalhes de Produtos Visualizados",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "catalog_product_view_count_total",
     "legendFormat": "Quantidade total de visualizações dos detalhes de um produto"
    }
   ]
  },
  {
   "title": "Quantidade Total de Itens no Carrinho",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "basket_total_items_Quantidade_total_de_itens_no_carrinho",
     "legendFormat": "Número atual de produtos no carrinho"
    }
   ]
  },
  {
   "title": "Flow do Carrinho",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "basket_add_to_cart_count_total", "legendFormat": "Total Produtos Adicionados " },
    {
     "expr": "basket_remove_from_cart_count_total",
     "legendFormat": "Total Produtos Removidos "
    }
   ]
  },
  {
   "title": "Total de Visualizações da Lista de Produtos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "catalog_product_list_count_total",
     "legendFormat": "Quantidade total de  visualizações da lista de produtos"
    }
   ]
  },
  {
   "title": "Total de Filtros Aplicados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "catalog_product_filter_count_total",
     "legendFormat": "Número total de requisições filtradas por tipo e marca"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta - Procura de Produtos",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(product_detail_response_time_milliseconds_sum[5m])) / sum(rate(product_detail_response_time_milliseconds_count[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribuição dos Tempos de Resposta - Procura",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(product_detail_response_time_milliseconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}