{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Request - Catalog",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "catalog_requests_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total Product Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "catalog_product_view_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Filters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "catalog_product_filter_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Product List",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "catalog_product_list_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}